### ISSUE TITLE
https://github.com/disc3110/space-travellers-hub

### ISSUE THREAD

**Issue by smunozmo** [disc3110/space-travellers-hub#25]
### Redux Space Travellers Hub Project

Link:

[https://github.com/disc3110/space-travellers-hub/projects/2](https://github.com/disc3110/space-travellers-hub/projects/2)

Two team members: 

@disc3110 and @smunozmo

**Comment by vichuge** [comment]
# Project invalidated 🚫 

Hi there, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Why does this happen ❓ ❓ ❓ 

You have submitted a project, that doesn't have the link to the GitHub project, please add it to the description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Emmyn5600** [comment]
Hi, 

Good job so far! 👏🏼 @smunozmo and @disc3110 

May I highlight the following:

- You included a link to their GitHub project:heavy_check_mark:
- Number of cards in Backlog are equal to 17..:heavy_check_mark:
- All tasks has been assigned to each one:heavy_check_mark:
- Required categories: `Setup, Fetch data, Lists render, Actions, Conditional components, Filters` has been listed and assigned.:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by smunozmo** [comment]
Thank you! @vichuge @Emmyn5600
